name: Deploy
on:
  push:

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - name: Checkout sources
        id: checkout
        uses: actions/checkout@v7
      - name: Upload pages artifact
        id: upload-pages-artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: src
      - name: Deploy pages
        id: deploy-pages
        uses: actions/deploy-pages@v5
